Repository dnd-side-project/dnd-8th-9-frontend, pull requests merged in 2023-03, with the labels that each got.

#97 Feat: 리뷰 작성 컴포넌트 구현
  assets/icons/delete.svg
  assets/icons/heart.svg
  assets/icons/index.ts
  assets/images/index.ts
  assets/images/uploadImage.svg
  components/ReviewForm/Detail/Detail.styled.tsx
  components/ReviewForm/Detail/Detail.tsx
  components/ReviewForm/SelectMenu/SelectMenu.styed.tsx
  components/ReviewForm/SelectMenu/SelectMenu.tsx
  components/ReviewForm/SelectSizeDangdo/SelectSizeDangdo.styled.tsx
  components/ReviewForm/SelectSizeDangdo/SelectSizeDangdo.tsx
  components/ReviewForm/Submitted/Submitted.styled.tsx
  components/ReviewForm/Submitted/Submitted.tsx
  components/shared/Card/Card.styled.tsx
  components/shared/Card/Card.tsx
  components/shared/ImageWrap/ImageWrap.styled.tsx
  components/shared/ImageWrap/ImageWrap.tsx
  components/shared/MenuCard/MenuCard.styled.tsx
  components/shared/MenuCard/MenuCard.tsx
  components/store/StoreHero/ReviewInfo/ReviewInfo.tsx
  components/store/review/OverallStats/OverallStats.tsx
  components/store/review/Preview/Preview.tsx
  pages/store/[storeId]/menu/index.page.tsx
  pages/store/[storeId]/review/all/images.page.tsx
  pages/store/[storeId]/review/form/form.styled.tsx
  pages/store/[storeId]/review/form/index.page.tsx
  store/ReviewForm.ts
Labels: ✨feature

#98 Feat: 자주 사용되는 Text 모듈화
  assets/icons/heart.svg
  assets/icons/index.ts
  assets/icons/instagram.svg
  assets/icons/user.svg
  components/shared/Dangdo/Dangdo.styled.tsx
  components/shared/Dangdo/Dangdo.tsx
  components/shared/Icon/Icon.constant.tsx
  components/shared/Icon/Icon.styled.tsx
  components/shared/Icon/Icon.tsx
  components/shared/Nickname/Nickname.styled.tsx
  components/shared/Nickname/Nickname.tsx
  components/shared/Platform/Platform.styled.tsx
  components/shared/Platform/Platform.tsx
  components/shared/Tag/Tag.styled.tsx
  components/shared/Tag/Tag.tsx
  components/shared/Tag/common/CategoryTag.tsx
  components/shared/Text/Text.styled.tsx
  components/shared/Text/Text.tsx
  styles/emotion.d.ts
  styles/theme.ts
  utils/util.ts
Labels: ✨feature

#99 Feat: Card 컴포넌트 구현
  assets/icons/index.ts
  assets/icons/quote.svg
  components/shared/Card/Card.styled.tsx
  components/shared/Card/Card.tsx
  components/shared/Card/CardImage.styled.tsx
  components/shared/Card/CardImage.tsx
  components/shared/Card/MenuDoubleCard.tsx
  components/shared/Card/MenuSingleCard.tsx
  components/shared/Card/ReviewDoubleCard.tsx
  components/shared/Card/StoreDoubleCard.tsx
  components/shared/Card/StoreSingleCard.tsx
  components/shared/Platform/Platform.tsx
  styles/theme.ts
  utils/util.ts
Labels: ✨feature

#100 Feat: 홈피드 상단 구현
  api/types/randomMenuList.ts
  assets/icons/index.ts
  assets/icons/logo.svg
  assets/icons/search.svg
  assets/images/cake.svg
  assets/images/index.ts
  components/home/HomeHeader/HomeHeader.styled.tsx
  components/home/HomeHeader/HomeHeader.tsx
  components/home/HomeHero/HomeHero.styled.tsx
  components/home/HomeHero/HomeHero.tsx
  constants/navigations.ts
  constants/tabs.ts
  mocks/mockData/randomMenuList.ts
  mocks/mockData/storeList.ts
  pages/home/recommendation.page.tsx
  pages/home/recommendation/index.page.tsx
  styles/Global.tsx
Labels: ✨feature

#101 Feat: 홈피드 추천탭 구현
  components/home/HomeHero/HomeHero.tsx
  components/home/StoreRank/StoreRank.styled.tsx
  components/home/StoreRank/StoreRank.tsx
  components/shared/Button/Button.tsx
  components/shared/Card/Card.styled.tsx
  mocks/mockData/randomReviewList.ts
  pages/home/recommendation/index.page.tsx
  pages/home/recommendation/recommendation.styled.tsx
  utils/util.ts
Labels: ✨feature

#102 Feat: 홈피드 스토어 탭 구현
  assets/icons/check.svg
  assets/icons/index.ts
  assets/icons/sort.svg
  components/shared/Card/Card.styled.tsx
  components/shared/Card/Card.tsx
  components/shared/Card/StoreDoubleCard.tsx
  components/shared/Sort/Sort.styled.tsx
  components/shared/Sort/Sort.tsx
  pages/home/stores.page.tsx
Labels: ✨feature

#104 Feat: 필터링 모달 구현
  assets/icons/close.svg
  assets/icons/index.ts
  components/shared/FilterBar/FilterBar.styled.tsx
  components/shared/FilterBar/FilterBar.tsx
  components/shared/FilterModal/FilterModal.styled.tsx
  components/shared/FilterModal/FilterModal.tsx
  components/shared/Icon/Icon.constant.tsx
  components/shared/Input/Checkbox/CheckboxGroup.styled.tsx
  components/shared/Input/Checkbox/CheckboxGroup.tsx
  components/shared/Input/Radio/RadioGroup.styled.tsx
  components/shared/Input/Radio/RadioGroup.tsx
  components/shared/Sort/Sort.styled.tsx
  components/shared/Tab/Tab.styled.tsx
  components/shared/Tab/Tab.tsx
  package.json
  pages/home/reviews.page.tsx
  pages/home/stores.page.tsx
  store/filter.ts
  tsconfig.json
  yarn.lock
Labels: ✨feature

#105 Feat: 업체 상세 / 리뷰 / 사진 크게보기 기능 구현
  components/store/review/OverallStats/OverallStats.tsx
  components/store/review/Review/Review.tsx
  constants/navigations.ts
  constants/routes.ts
  pages/store/[storeId]/review/[reviewId]/image/image.styled.tsx
  pages/store/[storeId]/review/[reviewId]/image/index.page.tsx
Labels: ✨feature

#111 Fix: Navbar, GNB 에러 해결 및 디자인 수정
  assets/icons/home_nav.svg
  assets/icons/index.ts
  components/shared/Icon/Icon.constant.tsx
  components/shared/Layout/Layout.styled.tsx
  components/shared/Layout/Layout.tsx
  components/shared/Layout/MainLayout.tsx
  components/shared/Layout/SubLayout.tsx
  components/shared/Navbar/Navbar.styled.tsx
  components/shared/Navbar/Navbar.tsx
  constants/navigation.ts
  constants/navigations.ts
  constants/routes.ts
  constants/tabs.ts
  pages/_app.page.tsx
  pages/mypage/edit/nickname.page.tsx
  pages/mypage/edit/onboard/category.page.tsx
  pages/mypage/edit/onboard/index.page.tsx
  pages/mypage/edit/onboard/location.page.tsx
  pages/mypage/index.page.tsx
  pages/mypage/notice.page.tsx
  pages/mypage/review.page.tsx
  pages/mypage/settings.page.tsx
Labels: 🐞bug, 🛠️refactoring

#115 Feat: 마이페이지 및 로그아웃 구현
  assets/icons/index.ts
  assets/icons/logout.svg
  assets/icons/user.svg
  components/login/KakaoLogin.tsx
  components/mypage/LogoutModal/LogoutModal.styled.tsx
  components/mypage/LogoutModal/LogoutModal.tsx
  components/shared/GNB/GNB.tsx
  components/shared/Icon/Icon.constant.tsx
  components/shared/Nickname/Nickname.tsx
  pages/login/index.page.tsx
  pages/mypage/index.page.tsx
  pages/mypage/mypage.styled.tsx
  store/modal.ts
Labels: ✨feature

#116 Feat: 업체상세 / 리뷰 / 사진 모아보기 / 크게보기
  constants/navigations.ts
  constants/routes.ts
  pages/store/[storeId]/review/all/images.page.tsx
  pages/store/[storeId]/review/all/images/[imageId]/index.page.tsx
  pages/store/[storeId]/review/all/images/[imageId]/index.styled.tsx
Labels: ✨feature

#118 Feat: 검색페이지 구현
  assets/icons/index.ts
  assets/icons/search_close.svg
  assets/icons/trend_down.svg
  assets/icons/trend_new.svg
  assets/icons/trend_same.svg
  assets/icons/trend_up.svg
  components/search/SearchHistory/SearchHistory.styled.tsx
  components/search/SearchHistory/SearchHistory.tsx
  components/search/SearchNav/SearchNav.styled.tsx
  components/search/SearchNav/SearchNav.tsx
  components/search/Trending/Trending.styled.tsx
  components/search/Trending/Trending.tsx
  components/shared/Tab/Tab.tsx
  pages/search/index.page.tsx
  pages/search/result/menu.page.tsx
  pages/search/result/store.page.tsx
  pages/search/search.styled.tsx
  store/search.ts
Labels: ✨feature

#119 Feat: 사진 모아보기 / 크기보기 Navigation 디자인 및 변경 사항 적용, 라우팅 수정
  components/store/infoTable/Table/Table.styled.tsx
  components/store/infoTable/Table/Table.tsx
  constants/navigation.ts
  constants/navigations.ts
  constants/routes.ts
  pages/store/[storeId]/review/all.page.tsx
  pages/store/[storeId]/review/images/[imageId]/index.page.tsx
  pages/store/[storeId]/review/images/[imageId]/index.styled.tsx
  pages/store/[storeId]/review/images/images.styled.tsx
  pages/store/[storeId]/review/images/index.page.tsx
  pages/store/[storeId]/review/index.page.tsx
Labels: ✨feature, 🐞bug

#122 Feat: Review Form 제출 기능 구현
  components/ReviewForm/Detail/Detail.tsx
  components/store/review/Review/Review.tsx
  pages/store/[storeId]/review/form/index.page.tsx
  pages/store/[storeId]/review/index.page.tsx
  store/ReviewForm.ts
  store/review.ts
Labels: ✨feature

#123 검색페이지 검색 로직 추가
  components/shared/Card/Card.tsx
  pages/search/result/menu.page.tsx
  pages/search/result/store.page.tsx
  pages/search/search.styled.tsx
Labels: ✨feature

#124 Feat: 온보딩 페이지 구현
  .env
  api/types/onboard.ts
  assets/images/index.ts
  assets/images/onboardCake.svg
  components/login/KakaoLogin.tsx
  constants/navigation.ts
  constants/routes.ts
  mocks/mockData/category.ts
  mocks/mockData/location.ts
  pages/onboard/category.page.tsx
  pages/onboard/category/category.styled.tsx
  pages/onboard/category/index.page.tsx
  pages/onboard/location.page.tsx
  pages/onboard/location/index.page.tsx
  pages/onboard/location/location.styled.tsx
  pages/onboard/welcome/index.page.tsx
  pages/onboard/welcome/welcome.styled.tsx
  store/onboard.ts
  store/user.ts
Labels: ✨feature

#126 Feat: 마이페이지 맞춤 정보 수정 구현
  constants/navigation.ts
Labels: ✨feature

#131 Feat: 로그인 리다이렉트 페이지 구현
  assets/images/index.ts
  assets/images/logoIcon.svg
  components/shared/Layout/MainLayout.tsx
  pages/login/redirect/index.page.tsx
  pages/login/redirect/redirect.styled.tsx
  styles/emotion.d.ts
  styles/theme.ts
Labels: ✨feature

#132 Feat: 마이페이지 맞춤 정보 수정 구현
  components/onboard/Category/Category.styled.tsx
  components/onboard/Category/Category.tsx
  components/onboard/Location/Location.styled.tsx
  components/onboard/Location/Location.tsx
  pages/mypage/edit/onboard/category.page.tsx
  pages/mypage/edit/onboard/index.page.tsx
  pages/mypage/edit/onboard/location.page.tsx
  pages/mypage/onboard/category.page.tsx
  pages/mypage/onboard/index.page.tsx
  pages/mypage/onboard/location.page.tsx
  pages/mypage/onboard/onboard.styled.tsx
  pages/mypage/profile.page.tsx
  pages/onboard/category/category.styled.tsx
  pages/onboard/category/index.page.tsx
  pages/onboard/location/index.page.tsx
  pages/onboard/location/location.styled.tsx
Labels: ✨feature

#137 Feat: 검색 결과창 N Case 구현
  assets/images/index.ts
  assets/images/noResult.svg
  components/search/NoResult/NoResult.styled.tsx
  components/search/NoResult/NoResult.tsx
  pages/search/result/menu.page.tsx
Labels: ✨feature

#140 Style & Refactor: 업체 상세 정보 / 공지사항 탭 : 디자인 변경사항 반영
  api/types/menu.ts
  api/types/shared.ts
  api/types/store.ts
  components/store/SectionLayout/SectionLayout.tsx
  components/store/StoreHero/MainInfo/MainInfo.styled.tsx
  components/store/infoTable/NoticeInfo/NoticeInfo.styled.tsx
  components/store/infoTable/NoticeInfo/NoticeInfo.tsx
  components/store/infoTable/Packaging/Packaging.styled.tsx
  components/store/infoTable/Packaging/Packaging.tsx
  components/store/infoTable/PickupHours/PickupHours.tsx
  components/store/infoTable/Table/Table.styled.tsx
  components/store/infoTable/Table/Table.tsx
  components/store/infoTable/TableBox/TableBox.styled.tsx
  components/store/infoTable/TableBox/TableBox.tsx
  components/store/infoTable/Text/Text.styled.tsx
  components/store/infoTable/Text/Text.tsx
  components/store/infoTable/TextBox/TextBox.styled.tsx
  components/store/infoTable/TextBox/TextBox.tsx
  components/store/menu/MenuCaution/MenuCaution.tsx
  components/store/menu/MenuDesign/MenuDesign.tsx
  components/store/menu/MenuSize/MenuSize.tsx
  components/store/menu/MenuTaste/MenuTaste.tsx
  constants/tabs.ts
  pages/store/[storeId]/info/index.page.tsx
  pages/store/[storeId]/info/info.stories.tsx
  pages/store/[storeId]/info/info.styled.tsx
  pages/store/[storeId]/notice/index.page.tsx
  pages/store/[storeId]/notice/notice.styled.ts
Labels: 🛠️refactoring, 🎨 UI

#141 Refactor / Feat 업체 상세 메뉴리스트 - 디자인 변경사항 반영
  components/shared/Card/MenuSingleCard.tsx
  components/store/SectionLayout/SectionLayout.styled.tsx
  components/store/SectionLayout/SectionLayout.tsx
  pages/store/[storeId]/menu/index.page.tsx
  pages/store/[storeId]/menu/menu.styled.ts
Labels: ✨feature, 🛠️refactoring

#144 Feat: 업체 메뉴 상세 페이지 - 변경된 디자인 반영
  api/types/menu.ts
  assets/images/sizeCircle.svg
  components/store/menu/MenuCaution/MenuCaution.styled.tsx
  components/store/menu/MenuCaution/MenuCaution.tsx
  components/store/menu/MenuDesign/MenuDesign.styled.tsx
  components/store/menu/MenuDesign/MenuDesign.tsx
  components/store/menu/MenuHero/MenuHero.styled.tsx
  components/store/menu/MenuHero/MenuHero.tsx
  components/store/menu/MenuSize/MenuSize.styled.tsx
  components/store/menu/MenuSize/MenuSize.tsx
  components/store/menu/MenuTaste/MenuTaste.styled.tsx
  components/store/menu/MenuTaste/MenuTaste.tsx
  components/store/menu/index.ts
  mocks/mockData/menu.ts
  pages/store/[storeId]/menu/[menuId]/all.page.tsx
  pages/store/[storeId]/menu/[menuId]/index.page.tsx
  pages/store/[storeId]/menu/[menuId]/menuItem.styled.ts
Labels: 🛠️refactoring, 🎨 UI

#146 Refactor / Style : 업체 리뷰 페이지 - 변경된 디자인 반영
  api/types/review.ts
  components/ReviewFilter/ReviewFilter.styled.tsx
  components/ReviewFilter/ReviewFilter.tsx
  components/shared/Button/Button.styled.tsx
  components/shared/Dangdo/Dangdo.tsx
  components/shared/Sort/Sort.styled.tsx
  components/store/review/OverallStats/OverallStats.styled.tsx
  components/store/review/OverallStats/OverallStats.tsx
  components/store/review/Preview/Preview.styled.tsx
  components/store/review/Preview/Preview.tsx
  components/store/review/PreviewImage/PreviewImage.styled.tsx
  components/store/review/PreviewImage/PreviewImage.tsx
  components/store/review/Review/Review.styled.tsx
  components/store/review/Review/Review.tsx
  constants/routes.ts
  pages/store/[storeId]/menu/[menuId]/index.page.tsx
  pages/store/[storeId]/menu/[menuId]/menuItem.styled.ts
  pages/store/[storeId]/review/[reviewId]/image/image.styled.tsx
  pages/store/[storeId]/review/index.page.tsx
  pages/store/[storeId]/review/review.styled.tsx
  utils/util.ts
Labels: 🛠️refactoring, 🎨 UI

#148 Feat: 주문 양식 컴포넌트 구현 및 모달 구현
  api/types/shared.ts
  api/types/store.ts
  assets/icons/copy.svg
  assets/icons/index.ts
  components/shared/ModalMessage/ModalMessage.styled.tsx
  components/shared/ModalMessage/ModalMessage.tsx
  mocks/mockData/store.ts
  pages/store/[storeId]/order/index.page.tsx
  pages/store/[storeId]/order/order.styled.ts
  store/modal.ts
Labels: ✨feature
