Repository dnd-side-project/dnd-8th-9-frontend, pull requests merged in 2023-02, with the labels that each got.

#6 Chore: React Query, Storybook, Zustand, Emotion 설치 및 세팅
  .babelrc
  .eslintrc.json
  .storybook/main.js
  .storybook/preview.js
  api/api.ts
  api/type.ts
  components/Button/Button.stories.tsx
  components/Button/Button.tsx
  components/Button/button.css
  components/Task/Task.styled.tsx
  components/Task/Task.tsx
  package.json
  pages/_app.tsx
  store/store.ts
  styles/Global.tsx
  styles/emotion.d.ts
  styles/globals.css
  styles/theme.ts
  yarn.lock
Labels: 🧹chore

#11 feat: 공통 Layout 적용
  components/Layout/Layout.styled.tsx
  components/Layout/Layout.tsx
  pages/_app.tsx
Labels: ✨feature

#17 Chore: Storybook 배포
  .github/chromatic.yml
  build-storybook.log
  package.json
  yarn.lock
Labels: 🧹chore

#19 Feat: Table 컴포넌트 구현
  components/Table/Table.styled.tsx
  components/Table/Table.tsx
  pages/store/[storeId]/notice/index.tsx
  styles/emotion.d.ts
  styles/theme.ts
Labels: ✨feature

#21 Fix: Storybook에서 theme, global style 적용 안되는 이슈
  .storybook/preview.js
Labels: 🐞bug

#24 Chore: MSW 설치 및 세팅
  .eslintrc.json
  api/api.ts
  api/type.ts
  components/Task/Task.tsx
  mocks/browser.ts
  mocks/handlers/index.ts
  mocks/handlers/store.ts
  mocks/index.ts
  mocks/server.ts
  package.json
  pages/_app.tsx
  pages/index.tsx
  public/mockServiceWorker.js
  tsconfig.json
  yarn.lock
Labels: 🧹chore

#28 Feat: 업체페이지 Mocking
  api/fetchers/store.ts
  api/index.ts
  api/queries/store.ts
  api/requestUrl.ts
  api/types/error.ts
  mocks/handlers/store.ts
  pages/store/[storeId]/menu/index.tsx
  pages/store/index.tsx
Labels: ✨feature

#29 Feat: Review 페이지 구현
  assets/icons/heart.svg
  components/Carousel/Carousel.styled.tsx
  components/Carousel/Carousel.tsx
  next.config.js
  package-lock.json
  package.json
  pages/store/[storeId]/review/index.tsx
  pages/store/[storeId]/review/review.styled.ts
  public/mockServiceWorker.js
  styles/Global.tsx
  yarn.lock
Labels: ✨feature

#33 Fix: Storybook Build Error
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  pages/store/[storeId]/menu/menu.stories.tsx
  yarn.lock
Labels: 🐞bug

#38 Chore: Storybook 추가 설정
  .storybook/main.js
  .storybook/preview.js
  package.json
  yarn.lock
Labels: 🧹chore

#39 Feat: 버튼 컴포넌트 구현
  .eslintrc.json
  assets/icons/bookmark.svg
  assets/icons/instagram.svg
  components/shared/Button/Button.stories.tsx
  components/shared/Button/Button.tsx
  components/shared/Button/button.styled.ts
  styles/Global.tsx
Labels: ✨feature

#41 Feat: Tab 컴포넌트 구현
  components/Button/Button.stories.tsx
  components/Button/Button.tsx
  components/Button/button.css
  components/shared/Tab/Tab.tsx
  components/shared/Tab/tab.styled.ts
  constants/navigations.ts
  styles/Global.tsx
  tsconfig.json
Labels: ✨feature

#46 Fix: Storybook Next.js Router 이슈 해결
  .storybook/main.js
  .storybook/preview.js
  package.json
  yarn.lock
Labels: 🐞bug

#47 Feat: Tag 컴포넌트 구현
  assets/icons/delivery.svg
  assets/icons/store.svg
  components/shared/Tag/Tag.stories.tsx
  components/shared/Tag/Tag.tsx
  components/shared/Tag/tag.styled.ts
Labels: ✨feature

#40 Feat: OverallStats 컴포넌트 구현
  assets/icons/pencil.svg
  components/Carousel/Carousel.styled.tsx
  components/OverallStats/OverallStats.stories.tsx
  components/OverallStats/OverallStats.styled.tsx
  components/OverallStats/OverallStats.tsx
  components/ProgressBar/ProgressBar.styled.tsx
  components/ProgressBar/ProgressBar.tsx
  components/Review/Review.styled.tsx
  components/Table/Table.tsx
  pages/store/[storeId]/review/index.tsx
  styles/emotion.d.ts
  styles/theme.ts
Labels: ✨feature

#49 Feat: Tab 스토리 추가
  components/shared/Tab/Tab.stories.tsx
  components/shared/Tab/Tab.tsx
Labels: ✨feature

#50 Refactor: OverallStats 컴포넌트 리팩토링
  components/OverallStats/OverallStats.styled.tsx
  components/OverallStats/OverallStats.tsx
  components/ProgressBar/ProgressBar.styled.tsx
  styles/emotion.d.ts
  styles/theme.ts
Labels: 🛠️refactoring

#54 Feat: Review 컴포넌트 UI 변경사항 추가
  assets/icons/like.svg
  components/Review/Review.styled.tsx
  components/Review/Review.tsx
  mocks/mockData/review.ts
  pages/store/[storeId]/review/index.tsx
Labels: ✨feature

#55 Feat: Info 컴포넌트 구현
  components/Table/Table.styled.tsx
  components/TableBox/TableBox.styled.tsx
  components/TableBox/TableBox.tsx
  pages/store/[storeId]/info/index.tsx
  pages/store/[storeId]/info/info.stories.tsx
  pages/store/[storeId]/info/info.styled.tsx
  pages/store/[storeId]/notice/index.tsx
  pages/store/[storeId]/notice/notice.stories.tsx
  pages/store/[storeId]/notice/notice.styled.ts
  styles/emotion.d.ts
  styles/theme.ts
Labels: ✨feature

#65 fix: pages에서 story, styled 파일들 ui폴더로 분리
  pages/store/[storeId]/menu/[menuId]/index.tsx
  pages/store/[storeId]/menu/index.tsx
  pages/store/[storeId]/notice/index.tsx
  pages/store/[storeId]/order/index.tsx
  ui/store/[storeId]/info/info.stories.tsx
  ui/store/[storeId]/info/info.styled.tsx
  ui/store/[storeId]/menu/[menuId]/menuItem.stories.tsx
  ui/store/[storeId]/menu/[menuId]/menuItem.styled.ts
  ui/store/[storeId]/menu/menu.stories.tsx
  ui/store/[storeId]/menu/menu.styled.ts
  ui/store/[storeId]/notice/notice.stories.tsx
  ui/store/[storeId]/notice/notice.styled.ts
  ui/store/[storeId]/order/order.stories.tsx
  ui/store/[storeId]/order/order.styled.ts
  ui/store/[storeId]/review/review.stories.tsx
Labels: 🐞bug

#64 Feat: 하단 GNB 컴포넌트 구현
  assets/icons/bookmark.svg
  assets/icons/home.svg
  assets/icons/mypage.svg
  assets/icons/search.svg
  components/shared/GNB/GNB.styled.tsx
  components/shared/GNB/GNB.tsx
  constants/navigations.ts
  pages/_app.tsx
Labels: ✨feature

#63 Feat: Notice 컴포넌트 구현
  components/NoticeInfo/NoticeInfo.styled.tsx
  components/NoticeInfo/NoticeInfo.tsx
  components/Packaging/Packaging.styled.tsx
  components/Packaging/Packaging.tsx
  components/PickupHours/PickupHours.tsx
  components/Table/Table.styled.tsx
  components/TableBox/TableBox.tsx
  components/Text/Text.styled.tsx
  components/Text/Text.tsx
  components/TextBox/TextBox.styled.tsx
  components/TextBox/TextBox.tsx
  pages/store/[storeId]/notice/index.tsx
  styles/emotion.d.ts
  styles/theme.ts
Labels: ✨feature

#62 Feat: Icon 컴포넌트 만들기 + 아이콘 모두 추가
  assets/icons/arrow-down.svg
  assets/icons/arrow-up.svg
  assets/icons/ellipsis.svg
  assets/icons/heart.svg
  assets/icons/index.ts
  assets/icons/info.svg
  assets/icons/left-arrow.svg
  assets/icons/like.svg
  assets/icons/map.svg
  assets/icons/ms_clap.svg
  assets/icons/ms_speaker.svg
  assets/icons/ms_tasty.svg
  assets/icons/ms_thinking.svg
  assets/icons/ms_warning.svg
  assets/icons/pencil.svg
  assets/icons/share.svg
  components/shared/Icon/Icon.constant.tsx
  components/shared/Icon/Icon.styled.tsx
  components/shared/Icon/Icon.tsx
Labels: ✨feature

#61 Feat: 업체페이지 메뉴 상세 상단 구현
  api/requestUrl.ts
  api/types/menu.ts
  api/types/review.ts
  api/types/shared.ts
  api/types/store.ts
  api/types/storeList.ts
  components/Carousel/Carousel.stories.tsx
  components/Carousel/Carousel.styled.tsx
  components/Carousel/Carousel.tsx
  components/Store/MenuHero/MenuHero.tsx
  components/Store/MenuHero/menuHero.styled.ts
  components/shared/Tag/Tag.stories.tsx
  components/shared/Tag/tag.styled.ts
  mocks/mockData/menu.ts
  mocks/mockData/menuList.ts
  mocks/mockData/review.ts
  pages/store/[storeId]/menu/[menuId]/index.tsx
  styles/Global.tsx
  styles/emotion.d.ts
  styles/theme.ts
  ui/store/[storeId]/menu/[menuId]/menuItem.styled.ts
Labels: ✨feature

#66 Feat: 업체페이지 상단 컴포넌트 구현
  api/types/review.ts
  components/OverallStats/OverallStats.tsx
  components/Review/Review.tsx
  components/Store/StoreHero/StoreHero.tsx
  components/Store/StoreHero/storeHero.styled.ts
  components/shared/Card/Card.tsx
  components/shared/Card/card.style.tsx
  components/shared/Icon/Icon.styled.tsx
  pages/store/[storeId]/menu/index.tsx
  styles/emotion.d.ts
  styles/theme.ts
  utils/util.ts
Labels: ✨feature

#69 hotfix: styled component 에러 해결
  ui/store/[storeId]/menu/menu.styled.ts
Labels: 🐞bug

#70 Feat: 리뷰 페이지 렌더링
  api/types/review.ts
  components/OverallStats/OverallStats.styled.tsx
  components/Review/Review.styled.tsx
  components/Review/Review.tsx
  components/shared/GNB/GNB.styled.tsx
  mocks/mockData/review.ts
  pages/store/[storeId]/review/index.tsx
Labels: ✨feature

#74 Refactor: Theme color 리팩토링
  components/Store/MenuHero/MenuHero.styled.tsx
  components/Store/StoreHero/StoreHero.styled.tsx
  components/Store/infoTable/NoticeInfo/NoticeInfo.styled.tsx
  components/Store/infoTable/Packaging/Packaging.styled.tsx
  components/Store/infoTable/Table/Table.styled.tsx
  components/Store/infoTable/TableBox/TableBox.styled.tsx
  components/Store/infoTable/Text/Text.styled.tsx
  components/Store/infoTable/TextBox/TextBox.styled.tsx
  components/Store/review/OverallStats/OverallStats.styled.tsx
  components/Store/review/ProgressBar/ProgressBar.styled.tsx
  components/Store/review/Review/Review.styled.tsx
  components/shared/Button/Button.stories.tsx
  components/shared/Button/Button.styled.tsx
  components/shared/Card/Card.styled.tsx
  components/shared/Card/Card.tsx
  components/shared/Carousel/Carousel.styled.tsx
  components/shared/GNB/GNB.styled.tsx
  components/shared/Tag/Tag.styled.tsx
  pages/store/[storeId]/menu/[menuId]/menuItem.styled.ts
  pages/store/[storeId]/order/order.styled.ts
  pages/store/[storeId]/review/review.styled.tsx
  styles/emotion.d.ts
  styles/theme.ts
Labels: 🛠️refactoring

#76 Fix: 빌드 이슈 해결
  components/store/MenuHero/MenuHero.styled.tsx
  components/store/MenuHero/MenuHero.tsx
  components/store/StoreHero/StoreHero.styled.tsx
  components/store/StoreHero/StoreHero.tsx
  components/store/infoTable/NoticeInfo/NoticeInfo.styled.tsx
  components/store/infoTable/NoticeInfo/NoticeInfo.tsx
  components/store/infoTable/Packaging/Packaging.styled.tsx
  components/store/infoTable/Packaging/Packaging.tsx
  components/store/infoTable/PickupHours/PickupHours.tsx
  components/store/infoTable/Table/Table.styled.tsx
  components/store/infoTable/Table/Table.tsx
  components/store/infoTable/TableBox/TableBox.styled.tsx
  components/store/infoTable/TableBox/TableBox.tsx
  components/store/infoTable/Text/Text.styled.tsx
  components/store/infoTable/Text/Text.tsx
  components/store/infoTable/TextBox/TextBox.styled.tsx
  components/store/infoTable/TextBox/TextBox.tsx
  components/store/review/OverallStats/OverallStats.stories.tsx
  components/store/review/OverallStats/OverallStats.styled.tsx
  components/store/review/OverallStats/OverallStats.tsx
  components/store/review/ProgressBar/ProgressBar.styled.tsx
  components/store/review/ProgressBar/ProgressBar.tsx
  components/store/review/Review/Review.stories.tsx
  components/store/review/Review/Review.styled.tsx
  components/store/review/Review/Review.tsx
  pages/store/[storeId]/menu/[menuId]/index.page.tsx
  pages/store/[storeId]/notice/index.page.tsx
  pages/store/[storeId]/review/all.page.tsx
  pages/store/[storeId]/review/index.page.tsx
Labels: 🐞bug

#81 Feat: 리뷰 Source 필터링 기능 구현
  components/ReviewFilter/ReviewFilter.styled.tsx
  components/ReviewFilter/ReviewFilter.tsx
  components/store/StoreHero/StoreHero.tsx
  components/store/infoTable/Table/Table.styled.tsx
  components/store/review/ProgressBar/ProgressBar.styled.tsx
  pages/store/[storeId]/review/all.page.tsx
Labels: ✨feature

#82 Feat: 리뷰 사진 모아보기 컴포넌트 구현
  .eslintrc.json
  components/shared/ImageWrap/ImageWrap.styled.tsx
  components/shared/ImageWrap/ImageWrap.tsx
  components/store/review/CountTitle/CountTitle.styled.tsx
  components/store/review/CountTitle/CountTitle.tsx
  components/store/review/Preview/Preview.styled.tsx
  components/store/review/Preview/Preview.tsx
  pages/store/[storeId]/review/all.page.tsx
  pages/store/[storeId]/review/all/images.page.tsx
  pages/store/[storeId]/review/all/images.styled.tsx
  pages/store/[storeId]/review/review.styled.tsx
Labels: ✨feature

#83 Feat: 업체 페이지 상단 컴포넌트 구현 마무리
  .storybook/preview.js
  api/types/review.ts
  api/types/shared.ts
  api/types/store.ts
  assets/icons/index.ts
  assets/icons/kakao.svg
  components/shared/Icon/Icon.constant.tsx
  components/store/ContentBox/ContentBox.styled.tsx
  components/store/ContentBox/ContentBox.tsx
  components/store/StoreHero/MainInfo/MainInfo.styled.tsx
  components/store/StoreHero/MainInfo/MainInfo.tsx
  components/store/StoreHero/OrderLink/OrderLink.styled.tsx
  components/store/StoreHero/OrderLink/OrderLink.tsx
  components/store/StoreHero/RecieveMethod/RecieveMethod.styled.tsx
  components/store/StoreHero/RecieveMethod/RecieveMethod.tsx
  components/store/StoreHero/ReviewInfo/ReviewInfo.styled.tsx
  components/store/StoreHero/ReviewInfo/ReviewInfo.tsx
  components/store/StoreHero/StoreHero.stories.tsx
  components/store/StoreHero/StoreHero.styled.tsx
  components/store/StoreHero/StoreHero.tsx
  components/store/review/Review/Review.stories.tsx
  components/store/review/Review/Review.tsx
  mocks/mockData/review.ts
  mocks/mockData/store.ts
  styles/theme.ts
Labels: ✨feature

#85 Feat: 메뉴 상세 페이지 구현
  .storybook/preview.js
  api/types/menu.ts
  assets/images/caution.svg
  assets/images/flavor.svg
  assets/images/index.ts
  assets/images/option.svg
  assets/images/size.svg
  assets/images/sizeCircle.svg
  components/shared/Tab/Tab.tsx
  components/store/menu/MenuCaution/MenuCaution.styled.tsx
  components/store/menu/MenuCaution/MenuCaution.tsx
  components/store/menu/MenuDesign/MenuDesign.styled.tsx
  components/store/menu/MenuDesign/MenuDesign.tsx
  components/store/menu/MenuHero/MenuHero.styled.tsx
  components/store/menu/MenuHero/MenuHero.tsx
  components/store/menu/MenuSize/MenuSize.styled.tsx
  components/store/menu/MenuSize/MenuSize.tsx
  components/store/menu/MenuTaste/MenuTaste.styled.tsx
  components/store/menu/MenuTaste/MenuTaste.tsx
  components/store/review/Review/Review.tsx
  mocks/mockData/menu.ts
  pages/store/[storeId]/menu/[menuId]/index.page.tsx
  pages/store/[storeId]/menu/[menuId]/menuItem.stories.tsx
  pages/store/[storeId]/menu/[menuId]/menuItem.styled.ts
Labels: ✨feature

#89 Feat: Navbar 추가 / GNB 수정 / Routes 추가
  assets/icons/arrow-left.svg
  assets/icons/bookmark-selected.svg
  assets/icons/bookmark.svg
  assets/icons/home-selected.svg
  assets/icons/home.svg
  assets/icons/index.ts
  assets/icons/profile-selected.svg
  assets/icons/profile.svg
  components/shared/GNB/GNB.styled.tsx
  components/shared/GNB/GNB.tsx
  components/shared/Icon/Icon.constant.tsx
  components/shared/Layout/Layout.styled.tsx
  components/shared/Layout/Layout.tsx
  components/shared/Navbar/Navbar.styled.tsx
  components/shared/Navbar/Navbar.tsx
  components/shared/Tab/Tab.stories.tsx
  constants/navigations.ts
  constants/routes.ts
  constants/tabs.ts
  hooks/useScrollPosition.ts
  next.config.js
  pages/_app.page.tsx
  pages/bookmark/design.page.tsx
  pages/bookmark/store.page.tsx
  pages/home/recommendation.page.tsx
  pages/home/reviews.page.tsx
  pages/home/stores.page.tsx
  pages/onboard/category.page.tsx
  pages/onboard/location.page.tsx
  pages/profile/edit/nickname.page.tsx
  pages/profile/edit/onboard/category.page.tsx
  pages/profile/edit/onboard/index.page.tsx
  pages/profile/edit/onboard/location.page.tsx
  pages/profile/index.page.tsx
  pages/profile/notice.page.tsx
  pages/profile/review.page.tsx
  pages/profile/settings.page.tsx
  pages/search/index.page.tsx
  pages/search/result/menu.page.tsx
  pages/search/result/store.page.tsx
  pages/store/[storeId]/index.page.tsx
  pages/store/[storeId]/info/index.page.tsx
  pages/store/[storeId]/info/info.styled.tsx
  pages/store/[storeId]/menu/[menuId]/all.page.tsx
  pages/store/[storeId]/menu/[menuId]/index.page.tsx
  pages/store/[storeId]/menu/[menuId]/menuItem.styled.ts
  pages/store/[storeId]/menu/index.page.tsx
  pages/store/[storeId]/menu/menu.styled.ts
  pages/store/[storeId]/notice/index.page.tsx
  pages/store/[storeId]/notice/notice.styled.ts
  pages/store/[storeId]/review/index.page.tsx
  pages/store/[storeId]/review/review.styled.tsx
  pages/store/index.page.tsx
Labels: ✨feature, 🛠️refactoring
